kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "rest-build"
spec:
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfile: "node('rest') {\nstage 'build'\nopenshiftBuild(buildConfig: 'rest-s2i', showBuildLogs: 'true')\nstage 'deploy'\nopenshiftDeploy(deploymentConfig: 'rest')\n}"
