apiVersion: v1
kind: Deployment
metadata:
  name: springboot-rest
spec:
  template:
    spec:
      containers:
        - readinessProbe:
            httpGet:
              path: /api/greeting
              port: 8080
              scheme: HTTP